kind: Service
apiVersion: v1
metadata:
  name: inventoryservice
spec:
  selector:
    app: inventory-service
  ports:
    - protocol: "TCP"
      # port sccessible inside cluster, what port does the service expose?
      port: 10001
      # target port = port  by default
      nodePort: 30001
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-deployment
  labels:
    app: inventory-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      containers:
        - name: inventory-service-kontener
          image: sadkowski/inventory-service
          ports:
            - containerPort: 80