kind: Service
apiVersion: v1
metadata:
  name: inventory
spec:
  selector:
    app: inventory-service
  ports:
    - protocol: "TCP"
      # port sccessible inside cluster, what port does the service expose?
      port: 10001
      # target port = port  by default
      # nodePort: 30002
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory
  labels:
    app: inventory
spec:
  replicas: 2
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      containers:
        - name: inventory-service-kontener
          image: szymonsadkowski/eksiegarnia_inventory:latest
          ports:
            - containerPort: 80
---
  apiVersion: v1
  kind: Service
  metadata:
    name: api-gateway
    labels:
      name: api-gateway
  spec:
    selector:
      app: api-gateway
    ports:
      - port: 10000
        nodePort: 30000
        protocol: "TCP"
    type: LoadBalancer
---
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: api-gateway
    labels:
      app: api-gateway
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: api-gateway
    template:
      metadata:
        labels:
          app: api-gateway
      spec:
        containers:
          - name: api-gateway-kontener
            image: szymonsadkowski/eksiegarnia_apigateway:latest
            ports:
              - containerPort: 80
---
  apiVersion: v1
  kind: Service
  metadata:
    name: orders
    labels:
      name: orders
  spec:
    selector:
      app: orders
    ports:
      - port: 10005
        protocol: "TCP"
    type: ClusterIP
---
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: orders
    labels:
      app: orders
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: orders
    template:
      metadata:
        labels:
          app: orders
      spec:
        containers:
          - name:  orders-kontener
            image: szymonsadkowski/eksiegarnia_orders:latest
            ports:
              - containerPort: 80
---
  apiVersion: v1
  kind: Service
  metadata:
    name: auth
    labels:
      name: auth
  spec:
    selector:
      app: auth
    ports:
      - port: 10010
        protocol: "TCP"
    type: ClusterIP
---
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: auth
    labels:
      app: auth
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: auth
    template:
      metadata:
        labels:
          app: auth
      spec:
        containers:
          - name: auth-kontener
            image: szymonsadkowski/eksiegarnia_auth:latest
            ports:
              - containerPort: 80
---
  apiVersion: v1
  kind: Service
  metadata:
    name: shipping
    labels:
      name: shipping
  spec:
    selector:
      app: shipping
    ports:
      - port: 10002
        protocol: "TCP"
    type: ClusterIP
---
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: shipping
    labels:
      app: shipping
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: shipping
    template:
      metadata:
        labels:
          app: shipping
      spec:
        containers:
          - name: shipping-kontener
            image: szymonsadkowski/eksiegarnia_shipping:latest
            ports:
              - containerPort: 80
